import Head from 'next/head';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';

//* Imports *///
import Button from './components/button.js';
import React from "react";
import CardList from './components/cardList.js';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
         <h1>Clase 10</h1>
         <div>
           <Button></Button>
         </div>
        <br></br>
        <CardList />
      </main>
    </>
  )
}

